### PR TITLE
Trus 4347

### PR DESCRIPTION
**Pull request by jackheslop96**
- Ensuring section/heading titles are rendered on the print
- Ensuring international address country is translated
- Ensuring passport/ID card country and expiry date are translated

### CODE REVIEW

**Comment by jackheslop96** [comment]
Screenshot 2021-07-15 at 12 49 19
Screenshot 2021-07-15 at 12 49 28
Screenshot 2021-07-15 at 12 49 44

**Comment by jackheslop96** [comment]
Screenshot 2021-07-15 at 12 49 19

**Comment by jackheslop96** [comment]
Screenshot 2021-07-15 at 12 49 28
Screenshot 2021-07-15 at 12 49 44

**Comment by jackheslop96** [comment]
Screenshot 2021-07-15 at 12 54 17
Screenshot 2021-07-15 at 12 54 30

**Review by BriWak — APPROVED** [review]

**Pull request merged**
